export interface Loc { id: string; name: string; x: number; y: number; w: number; h: number; spot: [number, number]; category: string; blurb: string; }
export const LOCATIONS: Loc[] = [
  { id: "square", name: "The Square", x: 515, y: 308, w: 18, h: 15, spot: [523, 315], category: "Social", blurb: "The main gathering spot for the whole town." },
  { id: "hall", name: "The Town Hall", x: 517, y: 295, w: 9, h: 6, spot: [523, 303], category: "Civic", blurb: "Voting, public debate, and the town's only clock." },
  { id: "market", name: "The Market", x: 503, y: 315, w: 8, h: 5, spot: [509, 319], category: "Work", blurb: "Wool stalls, sacks of oat grain, and goods fallen off carts." },
  { id: "tavern", name: "The Wet Fleece", x: 535, y: 313, w: 7, h: 5, spot: [539, 319], category: "Social", blurb: "The drinking den. Opens when the grain mill stops." },
  { id: "press", name: "The Daily Spit", x: 537, y: 297, w: 7, h: 5, spot: [541, 303], category: "Work", blurb: "The town newspaper press. Prints whatever got shouted in the square." },
  { id: "bank", name: "The Bank", x: 499, y: 297, w: 7, h: 5, spot: [505, 303], category: "Work", blurb: "The ledger of debts and favors between neighbors." },
  { id: "vault", name: "The Vault", x: 486, y: 298, w: 6, h: 4, spot: [491, 303], category: "Civic", blurb: "Storage for the town treasury's coins." },
  { id: "library", name: "The Library", x: 550, y: 299, w: 7, h: 5, spot: [555, 305], category: "Work", blurb: "Holds four books and one extremely serious librarian." },
  { id: "booth", name: "The Fork Booth", x: 518, y: 324, w: 7, h: 4, spot: [523, 329], category: "Civic", blurb: "Reproduction / cloning booth; one llama in, two out." },
  { id: "clinic", name: "The Clinic", x: 549, y: 316, w: 7, h: 4, spot: [553, 321], category: "Work", blurb: "Treats sprains, spit in the eye, and wounded pride." },
  { id: "school", name: "The School", x: 487, y: 316, w: 7, h: 4, spot: [493, 321], category: "Work", blurb: "Teaches the young to tell their grasses apart." },
  { id: "post", name: "The Post Office", x: 562, y: 310, w: 7, h: 4, spot: [567, 315], category: "Work", blurb: "Mail service for residents who never travel." },
  { id: "baths", name: "The Baths", x: 473, y: 310, w: 7, h: 4, spot: [479, 315], category: "Social", blurb: "Hot springs for high-tension conversation." },
  { id: "station", name: "The Station", x: 581, y: 305, w: 11, h: 5, spot: [589, 311], category: "Civic", blurb: "One cart a day, and it is always late." },
  { id: "barn", name: "The Barn", x: 455, y: 289, w: 11, h: 7, spot: [463, 297], category: "Rest", blurb: "Communal sleeping. Nobody admits to snoring." },
  { id: "shed", name: "The Shearing Shed", x: 463, y: 333, w: 9, h: 6, spot: [471, 339], category: "Work", blurb: "The shearing floor; morale drops the moment you walk in." },
  { id: "mill", name: "The Mill", x: 589, y: 331, w: 8, h: 7, spot: [595, 339], category: "Work", blurb: "The mill that grinds oats into more oats." },
  { id: "pens", name: "The Pens", x: 495, y: 337, w: 18, h: 12, spot: [503, 343], category: "Rest", blurb: "Quarantine pens for newcomers before they get adopted." },
  { id: "pond", name: "The Pond", x: 555, y: 339, w: 20, h: 13, spot: [565, 345], category: "Water", blurb: "Drink from the north side. Do not trust the south side." },
  { id: "dock", name: "The Dock", x: 563, y: 349, w: 8, h: 5, spot: [567, 353], category: "Social", blurb: "A wooden dock for the boat that never came back." },
  { id: "meadowW", name: "The West Meadow", x: 435, y: 313, w: 24, h: 20, spot: [449, 323], category: "Food", blurb: "Fresh high-grade pasture; fought over every single day." },
  { id: "meadowE", name: "The East Meadow", x: 591, y: 283, w: 24, h: 18, spot: [605, 293], category: "Food", blurb: "Sour grass; only ever eaten out of spite or grudge." },
  { id: "orchard", name: "The Orchard", x: 447, y: 349, w: 22, h: 16, spot: [459, 357], category: "Food", blurb: "A wild apple orchard everyone claims is communal." },
  { id: "trough", name: "The Trough", x: 513, y: 336, w: 6, h: 3, spot: [515, 337], category: "Food", blurb: "Oat trough at 7 a.m. Come early or go hungry." },
  { id: "fire", name: "The Fire", x: 527, y: 335, w: 5, h: 4, spot: [529, 337], category: "Social", blurb: "A night bonfire lit by nobody knows who." },
  { id: "board", name: "The Notice Board", x: 522, y: 310, w: 3, h: 2, spot: [523, 311], category: "Civic", blurb: "The notice board where townsfolk argue in writing." },
  { id: "stables", name: "The Stables", x: 505, y: 277, w: 9, h: 6, spot: [509, 284], category: "Rest", blurb: "Horses sleep here; the llamas pretend not to care." },
  { id: "granary", name: "The Granary", x: 495, y: 284, w: 8, h: 7, spot: [499, 292], category: "Work", blurb: "Oat reserves guarded like a state secret." },
  { id: "warehouse", name: "The Warehouse", x: 537, y: 285, w: 9, h: 6, spot: [541, 292], category: "Work", blurb: "Storage for everything the market could not sell." },
  { id: "chapel", name: "The Chapel", x: 595, y: 309, w: 7, h: 7, spot: [598, 317], category: "Civic", blurb: "Sunday prayers for extra grass and shorter winters." },
  { id: "inn", name: "The Wayfarer Inn", x: 559, y: 321, w: 10, h: 6, spot: [564, 328], category: "Social", blurb: "Beds for travellers who finally stopped walking." },
  { id: "smithy", name: "The Smithy", x: 581, y: 345, w: 8, h: 7, spot: [585, 353], category: "Work", blurb: "Horseshoes, hinges, and the occasional bent anvil." },
  { id: "farmhouse", name: "The Farmhouse", x: 499, y: 353, w: 11, h: 7, spot: [504, 361], category: "Rest", blurb: "Where oats begin their short and noble careers." },
  { id: "theatre", name: "The Fleece Theatre", x: 517, y: 354, w: 11, h: 6, spot: [522, 361], category: "Social", blurb: "Woolly performances nightly; the fleece always gets the last laugh." },
  { id: "depot", name: "The Depot", x: 467, y: 286, w: 7, h: 4, spot: [470, 291], category: "Work", blurb: "Carts, crates, and timetables nobody follows." },
  { id: "garage", name: "The Garage", x: 487, y: 286, w: 7, h: 4, spot: [490, 291], category: "Work", blurb: "Cart repairs; the queue is part of the service." },
  { id: "tower", name: "The Bell Tower", x: 528, y: 286, w: 7, h: 4, spot: [531, 291], category: "Civic", blurb: "Rings the hours, more or less on the hour." },
  { id: "arcade", name: "The Arcade", x: 563, y: 286, w: 7, h: 4, spot: [566, 291], category: "Social", blurb: "Game stalls and loud opinions under one roof." },
  { id: "forge", name: "The Forge", x: 465, y: 322, w: 8, h: 5, spot: [469, 328], category: "Work", blurb: "Second fire in town; first one for actual work." },
  { id: "lodge", name: "The Hunter Lodge", x: 538, y: 321, w: 8, h: 5, spot: [542, 327], category: "Social", blurb: "Trophies on the wall, stories taller than the wall." },
  { id: "observatory", name: "The Observatory", x: 578, y: 332, w: 9, h: 6, spot: [582, 339], category: "Civic", blurb: "Charts the stars; blames them for the weather." },
  { id: "exchange", name: "The Exchange", x: 472, y: 357, w: 9, h: 6, spot: [476, 364], category: "Work", blurb: "Oats futures, wool options, and strong coffee." },
  { id: "gatehouse", name: "The Northgate", x: 430, y: 185, w: 8, h: 5, spot: [434, 193], category: "Civic", blurb: "Two doors, one argument about which one is the front." },
  { id: "tollhouse", name: "The Tollhouse", x: 452, y: 180, w: 6, h: 4, spot: [455, 187], category: "Work", blurb: "Counts carts. Counts them twice if the driver argues." },
  { id: "barracks", name: "The Garrison", x: 475, y: 175, w: 10, h: 6, spot: [480, 184], category: "Rest", blurb: "Twelve beds, nine of them warm." },
  { id: "watchtower", name: "The North Watch", x: 500, y: 168, w: 6, h: 6, spot: [503, 177], category: "Civic", blurb: "Nothing to see. That is the whole job." },
  { id: "beacon", name: "The Beacon", x: 520, y: 160, w: 5, h: 5, spot: [522, 167], category: "Civic", blurb: "Lit on fog nights and bad news." },
  { id: "northStables", name: "The North Stables", x: 545, y: 178, w: 9, h: 6, spot: [549, 187], category: "Rest", blurb: "Post horses keep; they pay better than the rest." },
  { id: "curtainWall", name: "The Curtain Wall", x: 570, y: 180, w: 7, h: 4, spot: [573, 187], category: "Civic", blurb: "Repointed every spring, argued about every spring." },
  { id: "outerGate", name: "The Outer Gate", x: 600, y: 185, w: 6, h: 4, spot: [603, 192], category: "Civic", blurb: "Where the road stops pretending to be a street." },
  { id: "wharf", name: "The Wharf", x: 190, y: 400, w: 14, h: 5, spot: [197, 408], category: "Work", blurb: "Rope, tar, and the smell of money." },
  { id: "boathouse", name: "The Boathouse", x: 215, y: 420, w: 9, h: 6, spot: [219, 429], category: "Work", blurb: "Eight boats, four of them leak." },
  { id: "netloft", name: "The Net Loft", x: 240, y: 405, w: 8, h: 5, spot: [244, 412], category: "Work", blurb: "Holes patched until the patch has a patch." },
  { id: "saltWarehouse", name: "The Salt Warehouse", x: 270, y: 415, w: 9, h: 6, spot: [274, 424], category: "Work", blurb: "Weighed twice: once for the town, once for the tax." },
  { id: "ferrySlip", name: "The Ferry Slip", x: 300, y: 400, w: 8, h: 5, spot: [304, 408], category: "Civic", blurb: "The rope wears out faster than the boat." },
  { id: "chandlery", name: "The Chandlery", x: 330, y: 418, w: 7, h: 5, spot: [333, 425], category: "Work", blurb: "Tar, tallow, and small talk in that order." },
  { id: "riverWall", name: "The River Wall", x: 200, y: 440, w: 6, h: 4, spot: [203, 446], category: "Civic", blurb: "Holds the river off politely." },
  { id: "greenhouse", name: "The Glasshouse", x: 710, y: 290, w: 10, h: 6, spot: [715, 298], category: "Work", blurb: "Warm enough in January to argue in shirtsleeves." },
  { id: "orangery", name: "The Orangery", x: 735, y: 300, w: 8, h: 5, spot: [739, 307], category: "Work", blurb: "Citrus that will never be fruit." },
  { id: "apiary", name: "The Apiary", x: 760, y: 288, w: 6, h: 4, spot: [763, 294], category: "Work", blurb: "Twenty hives, one very confident neighbour." },
  { id: "bandstand", name: "The Bandstand", x: 790, y: 305, w: 8, h: 6, spot: [794, 312], category: "Social", blurb: "Brass on Sundays, silence on Mondays." },
  { id: "aviary", name: "The Aviary", x: 820, y: 292, w: 7, h: 5, spot: [823, 299], category: "Social", blurb: "Birds with better views than anyone." },
  { id: "hedgeMaze", name: "The Hedge Maze", x: 845, y: 310, w: 10, h: 7, spot: [850, 317], category: "Social", blurb: "Four entrances, one correct answer." },
  { id: "rosewalk", name: "The Rosewalk", x: 875, y: 295, w: 9, h: 6, spot: [879, 302], category: "Social", blurb: "Planted by someone who never saw them flower." },
  { id: "foundry", name: "The Foundry", x: 160, y: 140, w: 12, h: 8, spot: [166, 148], category: "Work", blurb: "Loud enough to be heard from the square." },
  { id: "kiln", name: "The Brick Kiln", x: 185, y: 155, w: 8, h: 6, spot: [189, 161], category: "Work", blurb: "Stoked at all hours by one very tired man." },
  { id: "oreShed", name: "The Ore Shed", x: 210, y: 135, w: 9, h: 6, spot: [214, 142], category: "Work", blurb: "Weighed, graded, and mildly resented." },
  { id: "foundryCrane", name: "The Ore Crane", x: 235, y: 150, w: 7, h: 5, spot: [238, 157], category: "Work", blurb: "Sways. Everyone calls that character." },
  { id: "quarryOffice", name: "The Quarry Office", x: 260, y: 140, w: 7, h: 5, spot: [263, 146], category: "Work", blurb: "Maps of a hole that keeps getting bigger." },
  { id: "charcoalYard", name: "The Charcoal Yard", x: 285, y: 158, w: 8, h: 5, spot: [289, 164], category: "Work", blurb: "Smells like a burnt Tuesday." },
  { id: "slagHeap", name: "The Slag Heap", x: 310, y: 145, w: 9, h: 6, spot: [314, 152], category: "Work", blurb: "Not a garden, despite appearances." },
  { id: "scriptorium", name: "The Scriptorium", x: 730, y: 140, w: 9, h: 6, spot: [734, 146], category: "Work", blurb: "Forty desks and a rule against talking." },
  { id: "lectureHall", name: "The Lecture Hall", x: 755, y: 155, w: 11, h: 7, spot: [760, 162], category: "Work", blurb: "Built so the back row could pretend to listen." },
  { id: "anatomy", name: "The Anatomy Room", x: 785, y: 138, w: 8, h: 5, spot: [789, 145], category: "Work", blurb: "Cold, well-lit, and heavily booked." },
  { id: "printHouse", name: "The Print House", x: 810, y: 152, w: 7, h: 5, spot: [813, 157], category: "Work", blurb: "Inks the colour of most bad ideas." },
  { id: "observatoryAnnex", name: "The Annex", x: 835, y: 135, w: 9, h: 6, spot: [839, 141], category: "Civic", blurb: "Where the instruments go to be recalibrated." },
  { id: "disputation", name: "The Disputation Hall", x: 860, y: 150, w: 8, h: 5, spot: [864, 156], category: "Social", blurb: "Shouting has a published schedule." },
  { id: "archive", name: "The Archive", x: 885, y: 138, w: 9, h: 6, spot: [889, 144], category: "Work", blurb: "Everything anyone ever wrote, badly indexed." },
  { id: "byre", name: "The Byre", x: 440, y: 440, w: 10, h: 6, spot: [445, 447], category: "Rest", blurb: "Warm, loud, and smells like the good barn." },
  { id: "threshingBarn", name: "The Threshing Barn", x: 465, y: 455, w: 11, h: 7, spot: [470, 462], category: "Work", blurb: "The drum is louder than the bell tower." },
  { id: "paddock", name: "The Paddock", x: 495, y: 438, w: 12, h: 8, spot: [501, 446], category: "Rest", blurb: "Fenced on three sides. The fourth is optimism." },
  { id: "dryingYard", name: "The Drying Yard", x: 525, y: 455, w: 8, h: 5, spot: [529, 461], category: "Work", blurb: "Sheaves stood up in rows like soldiers." },
  { id: "sheepfold", name: "The Sheepfold", x: 550, y: 440, w: 9, h: 6, spot: [554, 447], category: "Rest", blurb: "Counted twice a day, wrong once." },
  { id: "dairy", name: "The Dairy", x: 580, y: 452, w: 8, h: 6, spot: [584, 458], category: "Work", blurb: "Butter, cheese, and a very cold stone floor." },
  { id: "cemetery", name: "The Cemetery", x: 710, y: 490, w: 14, h: 9, spot: [717, 498], category: "Civic", blurb: "Kept tidy. Kept." },
  { id: "chapelOfBones", name: "The Chapel of Bones", x: 735, y: 515, w: 8, h: 6, spot: [739, 522], category: "Civic", blurb: "The roof is made from people who needed one." },
  { id: "hermitage", name: "The Hermitage", x: 760, y: 500, w: 6, h: 5, spot: [763, 506], category: "Rest", blurb: "One resident, voluntarily, for two years now." },
  { id: "charnel", name: "The Charnel House", x: 780, y: 520, w: 7, h: 5, spot: [783, 526], category: "Civic", blurb: "Reclaimed on schedule, reluctantly." },
  { id: "bonehouse", name: "The Bone House", x: 800, y: 505, w: 6, h: 4, spot: [803, 511], category: "Work", blurb: "Where they go when the chapel is full." },
  { id: "peatWorks", name: "The Peat Works", x: 170, y: 555, w: 10, h: 6, spot: [175, 561], category: "Work", blurb: "Cuts the bog into bricks of slow fire." },
  { id: "charcoalKiln", name: "The Charcoal Kiln", x: 200, y: 560, w: 8, h: 5, spot: [204, 565], category: "Work", blurb: "Burns a tree in nine days." },
  { id: "bogHut", name: "The Bog Hut", x: 230, y: 552, w: 6, h: 4, spot: [233, 557], category: "Rest", blurb: "Rent paid in gossip." },
  { id: "millpond", name: "The Millpond", x: 880, y: 180, w: 16, h: 10, spot: [888, 188], category: "Water", blurb: "Warm at the surface, colder every metre down." },
  { id: "northMeadow", name: "The North Meadow", x: 120, y: 300, w: 22, h: 18, spot: [131, 312], category: "Food", blurb: "Grass thin but honest." },
  { id: "southMeadow", name: "The South Meadow", x: 380, y: 570, w: 20, h: 16, spot: [390, 580], category: "Food", blurb: "The sheepfold's overflow field." },
  { id: "eastMeadow", name: "The East Meadow", x: 640, y: 480, w: 22, h: 18, spot: [651, 492], category: "Food", blurb: "Reclaimed from scrub in living memory." },
  { id: "westOrchard", name: "The West Orchard", x: 150, y: 440, w: 20, h: 15, spot: [160, 450], category: "Food", blurb: "Half windfall, half cider, all apology." },
  { id: "riverRun", name: "The River", x: 60, y: 180, w: 10, h: 140, spot: [65, 250], category: "Water", blurb: "Runs north to the ford and never once politely." },
  { id: "riverMouth", name: "The Lower River", x: 60, y: 340, w: 10, h: 100, spot: [65, 390], category: "Water", blurb: "Picks up speed where the bridge shadows it." },
  { id: "eastFen", name: "The East Fen", x: 950, y: 330, w: 18, h: 90, spot: [958, 375], category: "Water", blurb: "Reeds, mist, and one heron who owns the place." },
];
