/**
 * World grid dimensions — the single definition.
 *
 * This used to be duplicated: backend/src/map.ts declared Pe/vt/V and
 * frontend/src/canvas/constants.ts declared them again by hand. Growing the map
 * updated one and not the other, so the collision map indexed a 210x128 world
 * while the tiles it built were 1050x640: every square spot read as unwalkable
 * and every path request resolved to the wrong tile. The duplication was the
 * bug, not the numbers.
 *
 * The backend still owns the tile *generation* (createMap); this module owns the
 * numbers both sides have to agree on. backend/test/world.test.ts asserts the
 * two agree.
 */

/** Tiles across. 210 originally, 5x wider for the district build-out. */
export const Pe = 1050;

/** Tiles down. 128 originally, 5x taller for the district build-out. */
export const vt = 640;

/** World pixels per tile. */
export const V = 16;

export const WorldSize = {
  width: Pe * V,
  height: vt * V,
} as const;

/** A road segment in tile coordinates, inclusive on both ends. Always 2 tiles wide. */
export interface RoadRect {
  x1: number; y1: number; x2: number; y2: number;
}

/**
 * The road network.
 *
 * This lived only in frontend/src/canvas/scenery.ts, which left the backend's
 * tile generator carving roads at the pre-5x coordinates — three corridors that
 * now sit in open field two districts away from town. Two consumers, one table.
 *
 * GENERATED by scripts/emit-scenery-data.mjs - do not hand-edit. The generator
 * verifies the whole network against the real location table before it writes
 * anything: shared/src/netcheck.ts walks the road graph on the same 1-tile
 * expansion scenery.ts bakes into BLOCKED and fails the run on an orphan segment,
 * a road across a building, or a location no footpath reaches.
 * shared/test/road-network.test.ts asserts the same invariants in CI, plus that
 * every district keeps two independent routes to the core.
 */
// @generated:roads
export const ROADS: RoadRect[] = [
  { x1: 30, y1: 60, x2: 88, y2: 61 }, // North Ring
  { x1: 88, y1: 60, x2: 206, y2: 61 }, // North Ring
  { x1: 206, y1: 60, x2: 345, y2: 61 }, // North Ring
  { x1: 345, y1: 60, x2: 420, y2: 61 }, // North Ring
  { x1: 420, y1: 60, x2: 448, y2: 61 }, // North Ring
  { x1: 448, y1: 60, x2: 560, y2: 61 }, // North Ring
  { x1: 560, y1: 60, x2: 660, y2: 61 }, // North Ring
  { x1: 660, y1: 60, x2: 726, y2: 61 }, // North Ring
  { x1: 726, y1: 60, x2: 772, y2: 61 }, // North Ring
  { x1: 772, y1: 60, x2: 900, y2: 61 }, // North Ring
  { x1: 900, y1: 60, x2: 1019, y2: 61 }, // North Ring
  { x1: 30, y1: 166, x2: 71, y2: 167 }, // Northgate Blvd
  { x1: 71, y1: 166, x2: 88, y2: 167 }, // Northgate Blvd
  { x1: 88, y1: 166, x2: 145, y2: 167 }, // Northgate Blvd
  { x1: 145, y1: 166, x2: 206, y2: 167 }, // Northgate Blvd
  { x1: 206, y1: 166, x2: 268, y2: 167 }, // Northgate Blvd
  { x1: 268, y1: 166, x2: 345, y2: 167 }, // Northgate Blvd
  { x1: 345, y1: 166, x2: 420, y2: 167 }, // Northgate Blvd
  { x1: 420, y1: 166, x2: 448, y2: 167 }, // Northgate Blvd
  { x1: 448, y1: 166, x2: 560, y2: 167 }, // Northgate Blvd
  { x1: 560, y1: 166, x2: 620, y2: 167 }, // Northgate Blvd
  { x1: 620, y1: 166, x2: 660, y2: 167 }, // Northgate Blvd
  { x1: 660, y1: 166, x2: 726, y2: 167 }, // Northgate Blvd
  { x1: 726, y1: 166, x2: 772, y2: 167 }, // Northgate Blvd
  { x1: 772, y1: 166, x2: 842, y2: 167 }, // Northgate Blvd
  { x1: 842, y1: 166, x2: 900, y2: 167 }, // Northgate Blvd
  { x1: 900, y1: 166, x2: 1019, y2: 167 }, // Northgate Blvd
  { x1: 420, y1: 190, x2: 474, y2: 191 }, // Gatehouse Row
  { x1: 474, y1: 190, x2: 482, y2: 191 }, // Gatehouse Row
  { x1: 482, y1: 190, x2: 546, y2: 191 }, // Gatehouse Row
  { x1: 546, y1: 190, x2: 557, y2: 191 }, // Gatehouse Row
  { x1: 557, y1: 190, x2: 570, y2: 191 }, // Gatehouse Row
  { x1: 570, y1: 190, x2: 575, y2: 191 }, // Gatehouse Row
  { x1: 575, y1: 190, x2: 615, y2: 191 }, // Gatehouse Row
  { x1: 615, y1: 190, x2: 620, y2: 191 }, // Gatehouse Row
  { x1: 620, y1: 190, x2: 660, y2: 191 }, // Gatehouse Row
  { x1: 71, y1: 201, x2: 88, y2: 202 }, // Riverbank Rd
  { x1: 88, y1: 201, x2: 145, y2: 202 }, // West Approach
  { x1: 145, y1: 201, x2: 206, y2: 202 }, // Ironworks Way
  { x1: 206, y1: 201, x2: 268, y2: 202 }, // Kiln Row
  { x1: 268, y1: 201, x2: 345, y2: 202 }, // Quarry Way
  { x1: 345, y1: 201, x2: 420, y2: 202 }, // West Orbital
  { x1: 420, y1: 201, x2: 433, y2: 202 }, // Tollhouse Row
  { x1: 433, y1: 201, x2: 474, y2: 202 }, // West Loop
  { x1: 474, y1: 201, x2: 482, y2: 202 }, // Exchange Rd
  { x1: 482, y1: 201, x2: 546, y2: 202 }, // North St
  { x1: 546, y1: 201, x2: 557, y2: 202 }, // Chapel Row
  { x1: 557, y1: 201, x2: 570, y2: 202 }, // Press Row
  { x1: 570, y1: 201, x2: 575, y2: 202 }, // Station Row
  { x1: 575, y1: 201, x2: 615, y2: 202 }, // Chapel Rise
  { x1: 615, y1: 201, x2: 620, y2: 202 }, // Rosewalk Way
  { x1: 620, y1: 201, x2: 660, y2: 202 }, // East Orbital
  { x1: 660, y1: 201, x2: 726, y2: 202 }, // Commons Way
  { x1: 726, y1: 201, x2: 772, y2: 202 }, // Greenhouse Row
  { x1: 772, y1: 201, x2: 842, y2: 202 }, // Bandstand Row
  { x1: 842, y1: 201, x2: 900, y2: 202 }, // Aviary Row
  { x1: 900, y1: 201, x2: 1019, y2: 202 }, // College Ave
  { x1: 71, y1: 253, x2: 88, y2: 254 }, // Meadow Bank
  { x1: 88, y1: 253, x2: 145, y2: 254 }, // Wharf Approach
  { x1: 145, y1: 253, x2: 206, y2: 254 }, // Forge Row
  { x1: 206, y1: 253, x2: 268, y2: 254 }, // Slag Way
  { x1: 268, y1: 253, x2: 345, y2: 254 }, // Orchard Rd
  { x1: 345, y1: 253, x2: 420, y2: 254 }, // West Orbital S
  { x1: 420, y1: 253, x2: 433, y2: 254 }, // North St
  { x1: 433, y1: 253, x2: 474, y2: 254 }, // Tannery Row
  { x1: 474, y1: 253, x2: 482, y2: 254 }, // Centre Way
  { x1: 482, y1: 253, x2: 546, y2: 254 }, // Chapel Row
  { x1: 546, y1: 253, x2: 557, y2: 254 }, // Station Approach
  { x1: 557, y1: 253, x2: 570, y2: 254 }, // Library Row
  { x1: 570, y1: 253, x2: 575, y2: 254 }, // Press Row
  { x1: 575, y1: 253, x2: 615, y2: 254 }, // Station Row
  { x1: 615, y1: 253, x2: 620, y2: 254 }, // Meadow East
  { x1: 620, y1: 253, x2: 660, y2: 254 }, // East Orbital
  { x1: 660, y1: 253, x2: 726, y2: 254 }, // Commons Rd
  { x1: 726, y1: 253, x2: 772, y2: 254 }, // Hedge Row
  { x1: 772, y1: 253, x2: 842, y2: 254 }, // Bandstand Row
  { x1: 842, y1: 253, x2: 900, y2: 254 }, // Aviary Row
  { x1: 900, y1: 253, x2: 1019, y2: 254 }, // College Ave
  { x1: 30, y1: 325, x2: 71, y2: 326 }, // Wharf Bridge
  { x1: 71, y1: 325, x2: 88, y2: 326 }, // Wharf Bridge
  { x1: 88, y1: 325, x2: 145, y2: 326 }, // Wharf Bridge
  { x1: 30, y1: 333, x2: 71, y2: 334 }, // Lower Bridge
  { x1: 71, y1: 333, x2: 88, y2: 334 }, // Lower Bridge
  { x1: 88, y1: 333, x2: 145, y2: 334 }, // Lower Bridge
  { x1: 71, y1: 366, x2: 88, y2: 367 }, // West Bank
  { x1: 88, y1: 366, x2: 145, y2: 367 }, // Netloft Rd
  { x1: 145, y1: 366, x2: 206, y2: 367 }, // Salt Rd
  { x1: 206, y1: 366, x2: 268, y2: 367 }, // Chandlery Rd
  { x1: 268, y1: 366, x2: 345, y2: 367 }, // Wharf Rd
  { x1: 345, y1: 366, x2: 420, y2: 367 }, // West Orbital T
  { x1: 420, y1: 366, x2: 433, y2: 367 }, // Orchard Row
  { x1: 433, y1: 366, x2: 482, y2: 367 }, // West Loop
  { x1: 482, y1: 366, x2: 546, y2: 367 }, // Exchange Row
  { x1: 546, y1: 366, x2: 575, y2: 367 }, // Chapel Row
  { x1: 575, y1: 366, x2: 615, y2: 367 }, // Station Row
  { x1: 615, y1: 366, x2: 620, y2: 367 }, // Meadow East
  { x1: 620, y1: 366, x2: 660, y2: 367 }, // East Orbital T
  { x1: 660, y1: 366, x2: 726, y2: 367 }, // Commons Way
  { x1: 726, y1: 366, x2: 772, y2: 367 }, // Hollowmere Rd
  { x1: 772, y1: 366, x2: 842, y2: 367 }, // Hollow Lane
  { x1: 842, y1: 366, x2: 900, y2: 367 }, // Hollow Row
  { x1: 88, y1: 411, x2: 145, y2: 412 }, // Wharf Way
  { x1: 145, y1: 411, x2: 206, y2: 412 }, // Wharf Way
  { x1: 206, y1: 411, x2: 268, y2: 412 }, // Wharf Way
  { x1: 268, y1: 411, x2: 345, y2: 412 }, // Wharf Way
  { x1: 345, y1: 411, x2: 420, y2: 412 }, // Wharf Way
  { x1: 420, y1: 411, x2: 482, y2: 412 }, // Wharf Way
  { x1: 482, y1: 411, x2: 575, y2: 412 }, // Wharf Way
  { x1: 575, y1: 411, x2: 660, y2: 412 }, // Wharf Way
  { x1: 660, y1: 411, x2: 726, y2: 412 }, // Wharf Way
  { x1: 726, y1: 411, x2: 772, y2: 412 }, // Wharf Way
  { x1: 772, y1: 411, x2: 842, y2: 412 }, // Wharf Way
  { x1: 842, y1: 411, x2: 900, y2: 412 }, // Wharf Way
  { x1: 660, y1: 440, x2: 726, y2: 441 }, // Fen Link
  { x1: 726, y1: 440, x2: 772, y2: 441 }, // Fen Link
  { x1: 772, y1: 440, x2: 842, y2: 441 }, // Fen Link
  { x1: 842, y1: 440, x2: 900, y2: 441 }, // Fen Link
  { x1: 900, y1: 440, x2: 975, y2: 441 }, // Fen Link
  { x1: 975, y1: 440, x2: 1019, y2: 441 }, // Fen Link
  { x1: 30, y1: 464, x2: 71, y2: 465 }, // Farm Belt Way
  { x1: 71, y1: 464, x2: 88, y2: 465 }, // Farm Belt Way
  { x1: 88, y1: 464, x2: 145, y2: 465 }, // Farm Belt Way
  { x1: 145, y1: 464, x2: 206, y2: 465 }, // Farm Belt Way
  { x1: 206, y1: 464, x2: 268, y2: 465 }, // Farm Belt Way
  { x1: 268, y1: 464, x2: 345, y2: 465 }, // Farm Belt Way
  { x1: 345, y1: 464, x2: 420, y2: 465 }, // Farm Belt Way
  { x1: 420, y1: 464, x2: 482, y2: 465 }, // Farm Belt Way
  { x1: 482, y1: 464, x2: 575, y2: 465 }, // Farm Belt Way
  { x1: 575, y1: 464, x2: 660, y2: 465 }, // Farm Belt Way
  { x1: 660, y1: 464, x2: 726, y2: 465 }, // Farm Belt Way
  { x1: 726, y1: 464, x2: 772, y2: 465 }, // Farm Belt Way
  { x1: 772, y1: 464, x2: 842, y2: 465 }, // Farm Belt Way
  { x1: 842, y1: 464, x2: 900, y2: 465 }, // Farm Belt Way
  { x1: 900, y1: 464, x2: 1019, y2: 465 }, // Farm Belt Way
  { x1: 30, y1: 550, x2: 145, y2: 551 }, // Peat Way
  { x1: 145, y1: 550, x2: 212, y2: 551 }, // Peat Way
  { x1: 212, y1: 550, x2: 268, y2: 551 }, // Peat Way
  { x1: 268, y1: 550, x2: 345, y2: 551 }, // Peat Way
  { x1: 345, y1: 550, x2: 420, y2: 551 }, // Peat Way
  { x1: 420, y1: 550, x2: 482, y2: 551 }, // Peat Way
  { x1: 482, y1: 550, x2: 575, y2: 551 }, // Peat Way
  { x1: 575, y1: 550, x2: 726, y2: 551 }, // Peat Way
  { x1: 726, y1: 550, x2: 842, y2: 551 }, // Peat Way
  { x1: 842, y1: 550, x2: 900, y2: 551 }, // Peat Way
  { x1: 900, y1: 550, x2: 1019, y2: 551 }, // Peat Way
  { x1: 30, y1: 592, x2: 71, y2: 593 }, // South Ring
  { x1: 71, y1: 592, x2: 88, y2: 593 }, // South Ring
  { x1: 88, y1: 592, x2: 145, y2: 593 }, // South Ring
  { x1: 145, y1: 592, x2: 268, y2: 593 }, // South Ring
  { x1: 268, y1: 592, x2: 345, y2: 593 }, // South Ring
  { x1: 345, y1: 592, x2: 420, y2: 593 }, // South Ring
  { x1: 420, y1: 592, x2: 482, y2: 593 }, // South Ring
  { x1: 482, y1: 592, x2: 575, y2: 593 }, // South Ring
  { x1: 575, y1: 592, x2: 726, y2: 593 }, // South Ring
  { x1: 726, y1: 592, x2: 772, y2: 593 }, // South Ring
  { x1: 772, y1: 592, x2: 842, y2: 593 }, // South Ring
  { x1: 842, y1: 592, x2: 900, y2: 593 }, // South Ring
  { x1: 900, y1: 592, x2: 1019, y2: 593 }, // South Ring
  { x1: 420, y1: 270, x2: 433, y2: 271 }, // Chapel Row
  { x1: 433, y1: 270, x2: 474, y2: 271 }, // Chapel Row
  { x1: 474, y1: 270, x2: 482, y2: 271 }, // Chapel Row
  { x1: 482, y1: 270, x2: 546, y2: 271 }, // Chapel Row
  { x1: 546, y1: 270, x2: 557, y2: 271 }, // Chapel Row
  { x1: 557, y1: 270, x2: 570, y2: 271 }, // Chapel Row
  { x1: 570, y1: 270, x2: 575, y2: 271 }, // Chapel Row
  { x1: 575, y1: 270, x2: 620, y2: 271 }, // Chapel Row
  { x1: 620, y1: 270, x2: 660, y2: 271 }, // Chapel Row
  { x1: 420, y1: 302, x2: 433, y2: 303 }, // Bank St
  { x1: 433, y1: 302, x2: 474, y2: 303 }, // Bank St
  { x1: 474, y1: 302, x2: 482, y2: 303 }, // Bank St
  { x1: 482, y1: 302, x2: 546, y2: 303 }, // Bank St
  { x1: 557, y1: 302, x2: 570, y2: 303 }, // Bank St E
  { x1: 570, y1: 302, x2: 575, y2: 303 }, // Bank St E
  { x1: 575, y1: 302, x2: 592, y2: 303 }, // Bank St E
  { x1: 592, y1: 302, x2: 615, y2: 303 }, // Bank St E
  { x1: 615, y1: 302, x2: 620, y2: 303 }, // Bank St E
  { x1: 620, y1: 302, x2: 660, y2: 303 }, // Bank St E
  { x1: 660, y1: 302, x2: 700, y2: 303 }, // Bank St E
  { x1: 700, y1: 302, x2: 720, y2: 303 }, // Bank St E
  { x1: 420, y1: 328, x2: 433, y2: 329 }, // Main St
  { x1: 482, y1: 328, x2: 546, y2: 329 }, // Main St E
  { x1: 546, y1: 328, x2: 557, y2: 329 }, // Main St E
  { x1: 557, y1: 328, x2: 570, y2: 329 }, // Main St E
  { x1: 570, y1: 328, x2: 575, y2: 329 }, // Main St E
  { x1: 575, y1: 328, x2: 592, y2: 329 }, // Main St E
  { x1: 592, y1: 328, x2: 615, y2: 329 }, // Main St E
  { x1: 615, y1: 328, x2: 620, y2: 329 }, // Main St E
  { x1: 620, y1: 328, x2: 660, y2: 329 }, // Main St E
  { x1: 30, y1: 60, x2: 31, y2: 166 }, // West Ring
  { x1: 30, y1: 166, x2: 31, y2: 325 }, // West Ring
  { x1: 30, y1: 325, x2: 31, y2: 333 }, // West Ring
  { x1: 30, y1: 333, x2: 31, y2: 464 }, // West Ring
  { x1: 30, y1: 464, x2: 31, y2: 592 }, // West Ring
  { x1: 88, y1: 60, x2: 89, y2: 166 }, // Riverside Lane
  { x1: 88, y1: 166, x2: 89, y2: 201 }, // Riverside Lane
  { x1: 88, y1: 201, x2: 89, y2: 253 }, // Riverside Lane
  { x1: 88, y1: 253, x2: 89, y2: 325 }, // Riverside Lane
  { x1: 88, y1: 325, x2: 89, y2: 333 }, // Riverside Lane
  { x1: 88, y1: 333, x2: 89, y2: 366 }, // Riverside Lane
  { x1: 88, y1: 366, x2: 89, y2: 464 }, // Riverside Lane
  { x1: 71, y1: 166, x2: 72, y2: 201 }, // Riverbank Rd
  { x1: 71, y1: 201, x2: 72, y2: 253 }, // Riverbank Rd
  { x1: 71, y1: 253, x2: 72, y2: 325 }, // Riverbank Rd
  { x1: 71, y1: 325, x2: 72, y2: 333 }, // Riverbank Rd
  { x1: 71, y1: 333, x2: 72, y2: 366 }, // Riverbank Rd
  { x1: 71, y1: 366, x2: 72, y2: 464 }, // Riverbank Rd
  { x1: 145, y1: 166, x2: 146, y2: 201 }, // Moor Lane
  { x1: 145, y1: 201, x2: 146, y2: 253 }, // Moor Lane
  { x1: 145, y1: 253, x2: 146, y2: 325 }, // Moor Lane
  { x1: 145, y1: 325, x2: 146, y2: 333 }, // Moor Lane
  { x1: 145, y1: 333, x2: 146, y2: 366 }, // Moor Lane
  { x1: 145, y1: 366, x2: 146, y2: 464 }, // Moor Lane
  { x1: 145, y1: 464, x2: 146, y2: 592 }, // Moor Lane
  { x1: 206, y1: 60, x2: 207, y2: 166 }, // Ironworks Spur
  { x1: 206, y1: 166, x2: 207, y2: 201 }, // Ironworks Spur
  { x1: 206, y1: 201, x2: 207, y2: 253 }, // Ironworks Spur
  { x1: 206, y1: 253, x2: 207, y2: 366 }, // Ironworks Spur
  { x1: 206, y1: 366, x2: 207, y2: 464 }, // Ironworks Spur
  { x1: 212, y1: 464, x2: 213, y2: 550 }, // Peat Track
  { x1: 212, y1: 550, x2: 213, y2: 592 }, // Peat Track
  { x1: 268, y1: 166, x2: 269, y2: 201 }, // Quarry Rd
  { x1: 268, y1: 201, x2: 269, y2: 253 }, // Quarry Rd
  { x1: 268, y1: 253, x2: 269, y2: 366 }, // Quarry Rd
  { x1: 268, y1: 366, x2: 269, y2: 464 }, // Quarry Rd
  { x1: 268, y1: 464, x2: 269, y2: 592 }, // Quarry Rd
  { x1: 345, y1: 60, x2: 346, y2: 166 }, // West Radial
  { x1: 345, y1: 166, x2: 346, y2: 201 }, // West Radial
  { x1: 345, y1: 201, x2: 346, y2: 253 }, // West Radial
  { x1: 345, y1: 253, x2: 346, y2: 366 }, // West Radial
  { x1: 345, y1: 366, x2: 346, y2: 464 }, // West Radial
  { x1: 345, y1: 464, x2: 346, y2: 592 }, // West Radial
  { x1: 420, y1: 60, x2: 421, y2: 166 }, // North Spoke
  { x1: 420, y1: 166, x2: 421, y2: 201 }, // North Spoke
  { x1: 420, y1: 201, x2: 421, y2: 253 }, // North Spoke
  { x1: 420, y1: 253, x2: 421, y2: 270 }, // North Spoke
  { x1: 420, y1: 270, x2: 421, y2: 302 }, // North Spoke
  { x1: 420, y1: 302, x2: 421, y2: 328 }, // North Spoke
  { x1: 420, y1: 328, x2: 421, y2: 366 }, // North Spoke
  { x1: 420, y1: 366, x2: 421, y2: 464 }, // North Spoke
  { x1: 420, y1: 464, x2: 421, y2: 592 }, // North Spoke
  { x1: 433, y1: 201, x2: 434, y2: 253 }, // West Loop
  { x1: 433, y1: 253, x2: 434, y2: 270 }, // West Loop
  { x1: 433, y1: 270, x2: 434, y2: 302 }, // West Loop
  { x1: 433, y1: 302, x2: 434, y2: 328 }, // West Loop
  { x1: 433, y1: 328, x2: 434, y2: 366 }, // West Loop
  { x1: 474, y1: 201, x2: 475, y2: 253 }, // Exchange Rd
  { x1: 474, y1: 253, x2: 475, y2: 270 }, // Exchange Rd
  { x1: 474, y1: 270, x2: 475, y2: 302 }, // Exchange Rd
  { x1: 448, y1: 60, x2: 449, y2: 166 }, // Tollhouse Rd
  { x1: 448, y1: 166, x2: 449, y2: 201 }, // Tollhouse Rd
  { x1: 560, y1: 60, x2: 561, y2: 166 }, // Old Beacon Rd
  { x1: 560, y1: 166, x2: 561, y2: 201 }, // Old Beacon Rd
  { x1: 482, y1: 201, x2: 483, y2: 253 }, // West Ave
  { x1: 482, y1: 253, x2: 483, y2: 270 }, // West Ave
  { x1: 482, y1: 270, x2: 483, y2: 302 }, // West Ave
  { x1: 482, y1: 302, x2: 483, y2: 328 }, // West Ave
  { x1: 482, y1: 328, x2: 483, y2: 366 }, // West Ave
  { x1: 482, y1: 366, x2: 483, y2: 411 }, // West Ave
  { x1: 482, y1: 411, x2: 483, y2: 464 }, // West Ave
  { x1: 482, y1: 464, x2: 483, y2: 592 }, // West Ave
  { x1: 546, y1: 201, x2: 547, y2: 253 }, // East Ave
  { x1: 546, y1: 253, x2: 547, y2: 270 }, // East Ave
  { x1: 546, y1: 270, x2: 547, y2: 302 }, // East Ave
  { x1: 546, y1: 302, x2: 547, y2: 328 }, // East Ave
  { x1: 546, y1: 328, x2: 547, y2: 366 }, // East Ave
  { x1: 557, y1: 201, x2: 558, y2: 253 }, // Chapel Row
  { x1: 557, y1: 253, x2: 558, y2: 270 }, // Chapel Row
  { x1: 557, y1: 270, x2: 558, y2: 302 }, // Chapel Row
  { x1: 557, y1: 302, x2: 558, y2: 328 }, // Chapel Row
  { x1: 570, y1: 201, x2: 571, y2: 253 }, // Station Rd
  { x1: 570, y1: 253, x2: 571, y2: 270 }, // Station Rd
  { x1: 570, y1: 270, x2: 571, y2: 302 }, // Station Rd
  { x1: 570, y1: 302, x2: 571, y2: 328 }, // Station Rd
  { x1: 575, y1: 201, x2: 576, y2: 253 }, // Station Rd
  { x1: 575, y1: 253, x2: 576, y2: 270 }, // Station Rd
  { x1: 575, y1: 270, x2: 576, y2: 302 }, // Station Rd
  { x1: 575, y1: 302, x2: 576, y2: 328 }, // Station Rd
  { x1: 575, y1: 328, x2: 576, y2: 366 }, // Station Rd
  { x1: 575, y1: 366, x2: 576, y2: 411 }, // Station Rd
  { x1: 575, y1: 411, x2: 576, y2: 464 }, // Station Rd
  { x1: 575, y1: 464, x2: 576, y2: 592 }, // Station Rd
  { x1: 587, y1: 201, x2: 588, y2: 253 }, // Observatory Row
  { x1: 587, y1: 253, x2: 588, y2: 270 }, // Observatory Row
  { x1: 587, y1: 270, x2: 588, y2: 302 }, // Observatory Row
  { x1: 592, y1: 302, x2: 593, y2: 328 }, // Mill Row
  { x1: 615, y1: 201, x2: 616, y2: 253 }, // Chapel Row
  { x1: 615, y1: 253, x2: 616, y2: 270 }, // Chapel Row
  { x1: 615, y1: 270, x2: 616, y2: 302 }, // Chapel Row
  { x1: 615, y1: 302, x2: 616, y2: 328 }, // Chapel Row
  { x1: 620, y1: 60, x2: 621, y2: 166 }, // Chapel Row
  { x1: 620, y1: 166, x2: 621, y2: 201 }, // Chapel Row
  { x1: 620, y1: 201, x2: 621, y2: 253 }, // Chapel Row
  { x1: 620, y1: 253, x2: 621, y2: 270 }, // Chapel Row
  { x1: 620, y1: 270, x2: 621, y2: 302 }, // Chapel Row
  { x1: 620, y1: 302, x2: 621, y2: 328 }, // Chapel Row
  { x1: 620, y1: 328, x2: 621, y2: 366 }, // Chapel Row
  { x1: 660, y1: 60, x2: 661, y2: 166 }, // East Orbital Rd
  { x1: 660, y1: 166, x2: 661, y2: 201 }, // East Orbital Rd
  { x1: 660, y1: 201, x2: 661, y2: 253 }, // East Orbital Rd
  { x1: 660, y1: 253, x2: 661, y2: 270 }, // East Orbital Rd
  { x1: 660, y1: 270, x2: 661, y2: 302 }, // East Orbital Rd
  { x1: 660, y1: 302, x2: 661, y2: 328 }, // East Orbital Rd
  { x1: 660, y1: 328, x2: 661, y2: 366 }, // East Orbital Rd
  { x1: 660, y1: 366, x2: 661, y2: 411 }, // East Orbital Rd
  { x1: 660, y1: 411, x2: 661, y2: 440 }, // East Orbital Rd
  { x1: 660, y1: 440, x2: 661, y2: 464 }, // East Orbital Rd
  { x1: 700, y1: 201, x2: 701, y2: 253 }, // Commons Lane
  { x1: 700, y1: 253, x2: 701, y2: 302 }, // Commons Lane
  { x1: 700, y1: 302, x2: 701, y2: 366 }, // Commons Lane
  { x1: 700, y1: 366, x2: 701, y2: 411 }, // Commons Lane
  { x1: 700, y1: 411, x2: 701, y2: 464 }, // Commons Lane
  { x1: 700, y1: 464, x2: 701, y2: 592 }, // Commons Lane
  { x1: 726, y1: 60, x2: 727, y2: 166 }, // College Ave
  { x1: 726, y1: 166, x2: 727, y2: 201 }, // College Ave
  { x1: 726, y1: 201, x2: 727, y2: 253 }, // College Ave
  { x1: 726, y1: 253, x2: 727, y2: 302 }, // College Ave
  { x1: 726, y1: 302, x2: 727, y2: 366 }, // College Ave
  { x1: 726, y1: 366, x2: 727, y2: 440 }, // College Ave
  { x1: 726, y1: 440, x2: 727, y2: 464 }, // College Ave
  { x1: 726, y1: 464, x2: 727, y2: 592 }, // College Ave
  { x1: 720, y1: 201, x2: 721, y2: 253 }, // Greenhouse Row
  { x1: 720, y1: 253, x2: 721, y2: 302 }, // Greenhouse Row
  { x1: 720, y1: 302, x2: 721, y2: 366 }, // Greenhouse Row
  { x1: 720, y1: 366, x2: 721, y2: 411 }, // Greenhouse Row
  { x1: 720, y1: 411, x2: 721, y2: 464 }, // Greenhouse Row
  { x1: 855, y1: 201, x2: 856, y2: 253 }, // Bandstand Rd
  { x1: 855, y1: 253, x2: 856, y2: 366 }, // Bandstand Rd
  { x1: 855, y1: 366, x2: 856, y2: 464 }, // Bandstand Rd
  { x1: 855, y1: 464, x2: 856, y2: 592 }, // Bandstand Rd
  { x1: 772, y1: 60, x2: 773, y2: 166 }, // Hollowmere Lane
  { x1: 772, y1: 166, x2: 773, y2: 201 }, // Hollowmere Lane
  { x1: 772, y1: 201, x2: 773, y2: 253 }, // Hollowmere Lane
  { x1: 772, y1: 253, x2: 773, y2: 302 }, // Hollowmere Lane
  { x1: 772, y1: 302, x2: 773, y2: 366 }, // Hollowmere Lane
  { x1: 772, y1: 366, x2: 773, y2: 411 }, // Hollowmere Lane
  { x1: 772, y1: 411, x2: 773, y2: 440 }, // Hollowmere Lane
  { x1: 772, y1: 440, x2: 773, y2: 464 }, // Hollowmere Lane
  { x1: 772, y1: 464, x2: 773, y2: 592 }, // Hollowmere Lane
  { x1: 842, y1: 166, x2: 843, y2: 201 }, // Bonehouse Lane
  { x1: 842, y1: 201, x2: 843, y2: 253 }, // Bonehouse Lane
  { x1: 842, y1: 253, x2: 843, y2: 302 }, // Bonehouse Lane
  { x1: 842, y1: 302, x2: 843, y2: 366 }, // Bonehouse Lane
  { x1: 842, y1: 366, x2: 843, y2: 411 }, // Bonehouse Lane
  { x1: 842, y1: 411, x2: 843, y2: 440 }, // Bonehouse Lane
  { x1: 842, y1: 440, x2: 843, y2: 464 }, // Bonehouse Lane
  { x1: 842, y1: 464, x2: 843, y2: 550 }, // Bonehouse Lane
  { x1: 842, y1: 550, x2: 843, y2: 592 }, // Bonehouse Lane
  { x1: 900, y1: 60, x2: 901, y2: 166 }, // College Ave E
  { x1: 900, y1: 166, x2: 901, y2: 201 }, // College Ave E
  { x1: 900, y1: 201, x2: 901, y2: 253 }, // College Ave E
  { x1: 900, y1: 253, x2: 901, y2: 366 }, // College Ave E
  { x1: 900, y1: 366, x2: 901, y2: 411 }, // College Ave E
  { x1: 900, y1: 411, x2: 901, y2: 440 }, // College Ave E
  { x1: 900, y1: 440, x2: 901, y2: 464 }, // College Ave E
  { x1: 900, y1: 464, x2: 901, y2: 592 }, // College Ave E
  { x1: 975, y1: 60, x2: 976, y2: 166 }, // Fen Lane
  { x1: 975, y1: 166, x2: 976, y2: 201 }, // Fen Lane
  { x1: 975, y1: 201, x2: 976, y2: 253 }, // Fen Lane
  { x1: 975, y1: 253, x2: 976, y2: 366 }, // Fen Lane
  { x1: 975, y1: 366, x2: 976, y2: 440 }, // Fen Lane
  { x1: 975, y1: 440, x2: 976, y2: 464 }, // Fen Lane
  { x1: 975, y1: 464, x2: 976, y2: 592 }, // Fen Lane
  { x1: 1019, y1: 60, x2: 1020, y2: 166 }, // East Ring
  { x1: 1019, y1: 166, x2: 1020, y2: 201 }, // East Ring
  { x1: 1019, y1: 201, x2: 1020, y2: 253 }, // East Ring
  { x1: 1019, y1: 253, x2: 1020, y2: 366 }, // East Ring
  { x1: 1019, y1: 366, x2: 1020, y2: 440 }, // East Ring
  { x1: 1019, y1: 440, x2: 1020, y2: 464 }, // East Ring
  { x1: 1019, y1: 464, x2: 1020, y2: 592 }, // East Ring
];
// @end:roads

/**
 * Driveways: the short run of ground joining a building to its nearest street.
 *
 * Not a road network in its own right — these are not counted as carriageway by
 * anything, they carry no traffic lights and no lamps. They exist for one
 * reason: PAVED is grown from road tiles out to PAVE_REACH, so a building with
 * no tarmac beside it sits alone on grass and the district reads as a field with
 * sheds in it. 41 of the 87 built locations were in that state.
 *
 * Derived from ROADS and the locations by shared/src/access.ts rather than
 * hand-authored, so the set cannot drift out of step with either.
 */
// @generated:access-spurs
export const ACCESS_SPURS: RoadRect[] = [
  { x1: 515, y1: 302, x2: 515, y2: 308 }, // square
  { x1: 515, y1: 308, x2: 524, y2: 308 }, // square
  { x1: 517, y1: 302, x2: 517, y2: 300 }, // hall
  { x1: 517, y1: 300, x2: 521, y2: 300 }, // hall
  { x1: 503, y1: 328, x2: 503, y2: 319 }, // market
  { x1: 503, y1: 319, x2: 507, y2: 319 }, // market
  { x1: 546, y1: 313, x2: 541, y2: 313 }, // tavern
  { x1: 541, y1: 313, x2: 541, y2: 315 }, // tavern
  { x1: 537, y1: 302, x2: 537, y2: 301 }, // press
  { x1: 537, y1: 301, x2: 540, y2: 301 }, // press
  { x1: 499, y1: 302, x2: 499, y2: 301 }, // bank
  { x1: 499, y1: 301, x2: 502, y2: 301 }, // bank
  { x1: 486, y1: 302, x2: 486, y2: 301 }, // vault
  { x1: 486, y1: 301, x2: 489, y2: 301 }, // vault
  { x1: 557, y1: 302, x2: 556, y2: 302 }, // library
  { x1: 556, y1: 302, x2: 556, y2: 301 }, // library
  { x1: 518, y1: 328, x2: 518, y2: 327 }, // booth
  { x1: 518, y1: 327, x2: 521, y2: 327 }, // booth
  { x1: 546, y1: 316, x2: 549, y2: 316 }, // clinic
  { x1: 549, y1: 316, x2: 549, y2: 318 }, // clinic
  { x1: 482, y1: 316, x2: 487, y2: 316 }, // school
  { x1: 487, y1: 316, x2: 487, y2: 318 }, // school
  { x1: 570, y1: 310, x2: 568, y2: 310 }, // post
  { x1: 568, y1: 310, x2: 568, y2: 312 }, // post
  { x1: 482, y1: 310, x2: 479, y2: 310 }, // baths
  { x1: 479, y1: 310, x2: 479, y2: 312 }, // baths
  { x1: 592, y1: 305, x2: 591, y2: 305 }, // station
  { x1: 591, y1: 305, x2: 591, y2: 307 }, // station
  { x1: 455, y1: 302, x2: 455, y2: 295 }, // barn
  { x1: 455, y1: 295, x2: 460, y2: 295 }, // barn
  { x1: 482, y1: 333, x2: 471, y2: 333 }, // shed
  { x1: 471, y1: 333, x2: 471, y2: 336 }, // shed
  { x1: 589, y1: 328, x2: 589, y2: 331 }, // mill
  { x1: 589, y1: 331, x2: 593, y2: 331 }, // mill
  { x1: 495, y1: 328, x2: 495, y2: 337 }, // pens
  { x1: 495, y1: 337, x2: 504, y2: 337 }, // pens
  { x1: 575, y1: 349, x2: 570, y2: 349 }, // dock
  { x1: 570, y1: 349, x2: 570, y2: 351 }, // dock
  { x1: 527, y1: 328, x2: 527, y2: 335 }, // fire
  { x1: 527, y1: 335, x2: 529, y2: 335 }, // fire
  { x1: 522, y1: 302, x2: 522, y2: 310 }, // board
  { x1: 522, y1: 310, x2: 523, y2: 310 }, // board
  { x1: 505, y1: 270, x2: 505, y2: 277 }, // stables
  { x1: 505, y1: 277, x2: 509, y2: 277 }, // stables
  { x1: 495, y1: 302, x2: 495, y2: 290 }, // granary
  { x1: 495, y1: 290, x2: 499, y2: 290 }, // granary
  { x1: 546, y1: 285, x2: 545, y2: 285 }, // warehouse
  { x1: 545, y1: 285, x2: 545, y2: 288 }, // warehouse
  { x1: 592, y1: 309, x2: 595, y2: 309 }, // chapel
  { x1: 595, y1: 309, x2: 595, y2: 312 }, // chapel
  { x1: 557, y1: 321, x2: 559, y2: 321 }, // inn
  { x1: 559, y1: 321, x2: 559, y2: 324 }, // inn
  { x1: 575, y1: 345, x2: 581, y2: 345 }, // smithy
  { x1: 581, y1: 345, x2: 581, y2: 348 }, // smithy
  { x1: 499, y1: 366, x2: 499, y2: 359 }, // farmhouse
  { x1: 499, y1: 359, x2: 504, y2: 359 }, // farmhouse
  { x1: 517, y1: 366, x2: 517, y2: 359 }, // theatre
  { x1: 517, y1: 359, x2: 522, y2: 359 }, // theatre
  { x1: 474, y1: 286, x2: 473, y2: 286 }, // depot
  { x1: 473, y1: 286, x2: 473, y2: 288 }, // depot
  { x1: 482, y1: 286, x2: 487, y2: 286 }, // garage
  { x1: 487, y1: 286, x2: 487, y2: 288 }, // garage
  { x1: 546, y1: 286, x2: 534, y2: 286 }, // tower
  { x1: 534, y1: 286, x2: 534, y2: 288 }, // tower
  { x1: 570, y1: 286, x2: 569, y2: 286 }, // arcade
  { x1: 569, y1: 286, x2: 569, y2: 288 }, // arcade
  { x1: 482, y1: 322, x2: 472, y2: 322 }, // forge
  { x1: 472, y1: 322, x2: 472, y2: 324 }, // forge
  { x1: 546, y1: 321, x2: 545, y2: 321 }, // lodge
  { x1: 545, y1: 321, x2: 545, y2: 323 }, // lodge
  { x1: 575, y1: 332, x2: 578, y2: 332 }, // observatory
  { x1: 578, y1: 332, x2: 578, y2: 335 }, // observatory
  { x1: 482, y1: 357, x2: 480, y2: 357 }, // exchange
  { x1: 480, y1: 357, x2: 480, y2: 360 }, // exchange
  { x1: 430, y1: 190, x2: 430, y2: 189 }, // gatehouse
  { x1: 430, y1: 189, x2: 434, y2: 189 }, // gatehouse
  { x1: 448, y1: 180, x2: 452, y2: 180 }, // tollhouse
  { x1: 452, y1: 180, x2: 452, y2: 182 }, // tollhouse
  { x1: 475, y1: 166, x2: 475, y2: 175 }, // barracks
  { x1: 475, y1: 175, x2: 480, y2: 175 }, // barracks
  { x1: 500, y1: 166, x2: 500, y2: 168 }, // watchtower
  { x1: 500, y1: 168, x2: 503, y2: 168 }, // watchtower
  { x1: 520, y1: 166, x2: 520, y2: 164 }, // beacon
  { x1: 520, y1: 164, x2: 522, y2: 164 }, // beacon
  { x1: 545, y1: 190, x2: 545, y2: 183 }, // northStables
  { x1: 545, y1: 183, x2: 549, y2: 183 }, // northStables
  { x1: 570, y1: 190, x2: 570, y2: 183 }, // curtainWall
  { x1: 570, y1: 183, x2: 573, y2: 183 }, // curtainWall
  { x1: 600, y1: 190, x2: 600, y2: 188 }, // outerGate
  { x1: 600, y1: 188, x2: 603, y2: 188 }, // outerGate
  { x1: 206, y1: 400, x2: 203, y2: 400 }, // wharf
  { x1: 203, y1: 400, x2: 203, y2: 402 }, // wharf
  { x1: 215, y1: 411, x2: 215, y2: 420 }, // boathouse
  { x1: 215, y1: 420, x2: 219, y2: 420 }, // boathouse
  { x1: 240, y1: 411, x2: 240, y2: 409 }, // netloft
  { x1: 240, y1: 409, x2: 244, y2: 409 }, // netloft
  { x1: 268, y1: 415, x2: 270, y2: 415 }, // saltWarehouse
  { x1: 270, y1: 415, x2: 270, y2: 418 }, // saltWarehouse
  { x1: 300, y1: 411, x2: 300, y2: 404 }, // ferrySlip
  { x1: 300, y1: 404, x2: 304, y2: 404 }, // ferrySlip
  { x1: 330, y1: 411, x2: 330, y2: 418 }, // chandlery
  { x1: 330, y1: 418, x2: 333, y2: 418 }, // chandlery
  { x1: 206, y1: 440, x2: 205, y2: 440 }, // riverWall
  { x1: 205, y1: 440, x2: 205, y2: 442 }, // riverWall
  { x1: 720, y1: 290, x2: 719, y2: 290 }, // greenhouse
  { x1: 719, y1: 290, x2: 719, y2: 293 }, // greenhouse
  { x1: 726, y1: 300, x2: 735, y2: 300 }, // orangery
  { x1: 735, y1: 300, x2: 735, y2: 302 }, // orangery
  { x1: 772, y1: 288, x2: 765, y2: 288 }, // apiary
  { x1: 765, y1: 288, x2: 765, y2: 290 }, // apiary
  { x1: 772, y1: 305, x2: 790, y2: 305 }, // bandstand
  { x1: 790, y1: 305, x2: 790, y2: 308 }, // bandstand
  { x1: 842, y1: 292, x2: 826, y2: 292 }, // aviary
  { x1: 826, y1: 292, x2: 826, y2: 294 }, // aviary
  { x1: 855, y1: 310, x2: 854, y2: 310 }, // hedgeMaze
  { x1: 854, y1: 310, x2: 854, y2: 313 }, // hedgeMaze
  { x1: 900, y1: 295, x2: 883, y2: 295 }, // rosewalk
  { x1: 883, y1: 295, x2: 883, y2: 298 }, // rosewalk
  { x1: 160, y1: 166, x2: 160, y2: 147 }, // foundry
  { x1: 160, y1: 147, x2: 166, y2: 147 }, // foundry
  { x1: 185, y1: 166, x2: 185, y2: 160 }, // kiln
  { x1: 185, y1: 160, x2: 189, y2: 160 }, // kiln
  { x1: 206, y1: 135, x2: 210, y2: 135 }, // oreShed
  { x1: 210, y1: 135, x2: 210, y2: 138 }, // oreShed
  { x1: 235, y1: 166, x2: 235, y2: 154 }, // foundryCrane
  { x1: 235, y1: 154, x2: 238, y2: 154 }, // foundryCrane
  { x1: 260, y1: 166, x2: 260, y2: 144 }, // quarryOffice
  { x1: 260, y1: 144, x2: 263, y2: 144 }, // quarryOffice
  { x1: 285, y1: 166, x2: 285, y2: 162 }, // charcoalYard
  { x1: 285, y1: 162, x2: 289, y2: 162 }, // charcoalYard
  { x1: 310, y1: 166, x2: 310, y2: 150 }, // slagHeap
  { x1: 310, y1: 150, x2: 314, y2: 150 }, // slagHeap
  { x1: 726, y1: 140, x2: 730, y2: 140 }, // scriptorium
  { x1: 730, y1: 140, x2: 730, y2: 143 }, // scriptorium
  { x1: 755, y1: 166, x2: 755, y2: 161 }, // lectureHall
  { x1: 755, y1: 161, x2: 760, y2: 161 }, // lectureHall
  { x1: 772, y1: 138, x2: 785, y2: 138 }, // anatomy
  { x1: 785, y1: 138, x2: 785, y2: 140 }, // anatomy
  { x1: 810, y1: 166, x2: 810, y2: 156 }, // printHouse
  { x1: 810, y1: 156, x2: 813, y2: 156 }, // printHouse
  { x1: 835, y1: 166, x2: 835, y2: 140 }, // observatoryAnnex
  { x1: 835, y1: 140, x2: 839, y2: 140 }, // observatoryAnnex
  { x1: 860, y1: 166, x2: 860, y2: 154 }, // disputation
  { x1: 860, y1: 154, x2: 864, y2: 154 }, // disputation
  { x1: 900, y1: 138, x2: 893, y2: 138 }, // archive
  { x1: 893, y1: 138, x2: 893, y2: 141 }, // archive
  { x1: 440, y1: 464, x2: 440, y2: 445 }, // byre
  { x1: 440, y1: 445, x2: 445, y2: 445 }, // byre
  { x1: 465, y1: 464, x2: 465, y2: 461 }, // threshingBarn
  { x1: 465, y1: 461, x2: 470, y2: 461 }, // threshingBarn
  { x1: 482, y1: 438, x2: 495, y2: 438 }, // paddock
  { x1: 495, y1: 438, x2: 495, y2: 442 }, // paddock
  { x1: 525, y1: 464, x2: 525, y2: 459 }, // dryingYard
  { x1: 525, y1: 459, x2: 529, y2: 459 }, // dryingYard
  { x1: 575, y1: 440, x2: 558, y2: 440 }, // sheepfold
  { x1: 558, y1: 440, x2: 558, y2: 443 }, // sheepfold
  { x1: 575, y1: 452, x2: 580, y2: 452 }, // dairy
  { x1: 580, y1: 452, x2: 580, y2: 455 }, // dairy
  { x1: 726, y1: 490, x2: 723, y2: 490 }, // cemetery
  { x1: 723, y1: 490, x2: 723, y2: 494 }, // cemetery
  { x1: 726, y1: 515, x2: 735, y2: 515 }, // chapelOfBones
  { x1: 735, y1: 515, x2: 735, y2: 518 }, // chapelOfBones
  { x1: 772, y1: 500, x2: 765, y2: 500 }, // hermitage
  { x1: 765, y1: 500, x2: 765, y2: 502 }, // hermitage
  { x1: 772, y1: 520, x2: 780, y2: 520 }, // charnel
  { x1: 780, y1: 520, x2: 780, y2: 522 }, // charnel
  { x1: 772, y1: 505, x2: 800, y2: 505 }, // bonehouse
  { x1: 800, y1: 505, x2: 800, y2: 507 }, // bonehouse
  { x1: 170, y1: 550, x2: 170, y2: 555 }, // peatWorks
  { x1: 170, y1: 555, x2: 175, y2: 555 }, // peatWorks
  { x1: 212, y1: 560, x2: 207, y2: 560 }, // charcoalKiln
  { x1: 207, y1: 560, x2: 207, y2: 562 }, // charcoalKiln
  { x1: 230, y1: 550, x2: 230, y2: 552 }, // bogHut
  { x1: 230, y1: 552, x2: 233, y2: 552 }, // bogHut
];
// @end:access-spurs

/**
 * The subset of roads that get traffic lights. The 5x build-out multiplied the
 * junction count from 10 to 46, and signalling every rural crossroads made the
 * map read like an airport. Lamps are likewise laid along short roads only.
 */
// @generated:core-roads
export const CORE_ROADS: RoadRect[] = [
  { x1: 420, y1: 201, x2: 433, y2: 202 }, // Tollhouse Row
  { x1: 433, y1: 201, x2: 474, y2: 202 }, // West Loop
  { x1: 474, y1: 201, x2: 482, y2: 202 }, // Exchange Rd
  { x1: 482, y1: 201, x2: 546, y2: 202 }, // North St
  { x1: 546, y1: 201, x2: 557, y2: 202 }, // Chapel Row
  { x1: 557, y1: 201, x2: 570, y2: 202 }, // Press Row
  { x1: 570, y1: 201, x2: 575, y2: 202 }, // Station Row
  { x1: 575, y1: 201, x2: 615, y2: 202 }, // Chapel Rise
  { x1: 615, y1: 201, x2: 620, y2: 202 }, // Rosewalk Way
  { x1: 620, y1: 201, x2: 660, y2: 202 }, // East Orbital
  { x1: 420, y1: 253, x2: 433, y2: 254 }, // North St
  { x1: 433, y1: 253, x2: 474, y2: 254 }, // Tannery Row
  { x1: 474, y1: 253, x2: 482, y2: 254 }, // Centre Way
  { x1: 482, y1: 253, x2: 546, y2: 254 }, // Chapel Row
  { x1: 546, y1: 253, x2: 557, y2: 254 }, // Station Approach
  { x1: 557, y1: 253, x2: 570, y2: 254 }, // Library Row
  { x1: 570, y1: 253, x2: 575, y2: 254 }, // Press Row
  { x1: 575, y1: 253, x2: 615, y2: 254 }, // Station Row
  { x1: 615, y1: 253, x2: 620, y2: 254 }, // Meadow East
  { x1: 620, y1: 253, x2: 660, y2: 254 }, // East Orbital
  { x1: 420, y1: 366, x2: 433, y2: 367 }, // Orchard Row
  { x1: 433, y1: 366, x2: 482, y2: 367 }, // West Loop
  { x1: 482, y1: 366, x2: 546, y2: 367 }, // Exchange Row
  { x1: 546, y1: 366, x2: 575, y2: 367 }, // Chapel Row
  { x1: 575, y1: 366, x2: 615, y2: 367 }, // Station Row
  { x1: 615, y1: 366, x2: 620, y2: 367 }, // Meadow East
  { x1: 620, y1: 366, x2: 660, y2: 367 }, // East Orbital T
  { x1: 420, y1: 411, x2: 482, y2: 412 }, // Wharf Way
  { x1: 482, y1: 411, x2: 575, y2: 412 }, // Wharf Way
  { x1: 575, y1: 411, x2: 660, y2: 412 }, // Wharf Way
  { x1: 420, y1: 464, x2: 482, y2: 465 }, // Farm Belt Way
  { x1: 482, y1: 464, x2: 575, y2: 465 }, // Farm Belt Way
  { x1: 575, y1: 464, x2: 660, y2: 465 }, // Farm Belt Way
  { x1: 420, y1: 270, x2: 433, y2: 271 }, // Chapel Row
  { x1: 433, y1: 270, x2: 474, y2: 271 }, // Chapel Row
  { x1: 474, y1: 270, x2: 482, y2: 271 }, // Chapel Row
  { x1: 482, y1: 270, x2: 546, y2: 271 }, // Chapel Row
  { x1: 546, y1: 270, x2: 557, y2: 271 }, // Chapel Row
  { x1: 557, y1: 270, x2: 570, y2: 271 }, // Chapel Row
  { x1: 570, y1: 270, x2: 575, y2: 271 }, // Chapel Row
  { x1: 575, y1: 270, x2: 620, y2: 271 }, // Chapel Row
  { x1: 620, y1: 270, x2: 660, y2: 271 }, // Chapel Row
  { x1: 420, y1: 302, x2: 433, y2: 303 }, // Bank St
  { x1: 433, y1: 302, x2: 474, y2: 303 }, // Bank St
  { x1: 474, y1: 302, x2: 482, y2: 303 }, // Bank St
  { x1: 482, y1: 302, x2: 546, y2: 303 }, // Bank St
  { x1: 557, y1: 302, x2: 570, y2: 303 }, // Bank St E
  { x1: 570, y1: 302, x2: 575, y2: 303 }, // Bank St E
  { x1: 575, y1: 302, x2: 592, y2: 303 }, // Bank St E
  { x1: 592, y1: 302, x2: 615, y2: 303 }, // Bank St E
  { x1: 615, y1: 302, x2: 620, y2: 303 }, // Bank St E
  { x1: 620, y1: 302, x2: 660, y2: 303 }, // Bank St E
  { x1: 420, y1: 328, x2: 433, y2: 329 }, // Main St
  { x1: 482, y1: 328, x2: 546, y2: 329 }, // Main St E
  { x1: 546, y1: 328, x2: 557, y2: 329 }, // Main St E
  { x1: 557, y1: 328, x2: 570, y2: 329 }, // Main St E
  { x1: 570, y1: 328, x2: 575, y2: 329 }, // Main St E
  { x1: 575, y1: 328, x2: 592, y2: 329 }, // Main St E
  { x1: 592, y1: 328, x2: 615, y2: 329 }, // Main St E
  { x1: 615, y1: 328, x2: 620, y2: 329 }, // Main St E
  { x1: 620, y1: 328, x2: 660, y2: 329 }, // Main St E
  { x1: 420, y1: 201, x2: 421, y2: 253 }, // North Spoke
  { x1: 420, y1: 253, x2: 421, y2: 270 }, // North Spoke
  { x1: 420, y1: 270, x2: 421, y2: 302 }, // North Spoke
  { x1: 420, y1: 302, x2: 421, y2: 328 }, // North Spoke
  { x1: 420, y1: 328, x2: 421, y2: 366 }, // North Spoke
  { x1: 420, y1: 366, x2: 421, y2: 464 }, // North Spoke
  { x1: 433, y1: 201, x2: 434, y2: 253 }, // West Loop
  { x1: 433, y1: 253, x2: 434, y2: 270 }, // West Loop
  { x1: 433, y1: 270, x2: 434, y2: 302 }, // West Loop
  { x1: 433, y1: 302, x2: 434, y2: 328 }, // West Loop
  { x1: 433, y1: 328, x2: 434, y2: 366 }, // West Loop
  { x1: 474, y1: 201, x2: 475, y2: 253 }, // Exchange Rd
  { x1: 474, y1: 253, x2: 475, y2: 270 }, // Exchange Rd
  { x1: 474, y1: 270, x2: 475, y2: 302 }, // Exchange Rd
  { x1: 482, y1: 201, x2: 483, y2: 253 }, // West Ave
  { x1: 482, y1: 253, x2: 483, y2: 270 }, // West Ave
  { x1: 482, y1: 270, x2: 483, y2: 302 }, // West Ave
  { x1: 482, y1: 302, x2: 483, y2: 328 }, // West Ave
  { x1: 482, y1: 328, x2: 483, y2: 366 }, // West Ave
  { x1: 482, y1: 366, x2: 483, y2: 411 }, // West Ave
  { x1: 482, y1: 411, x2: 483, y2: 464 }, // West Ave
  { x1: 546, y1: 201, x2: 547, y2: 253 }, // East Ave
  { x1: 546, y1: 253, x2: 547, y2: 270 }, // East Ave
  { x1: 546, y1: 270, x2: 547, y2: 302 }, // East Ave
  { x1: 546, y1: 302, x2: 547, y2: 328 }, // East Ave
  { x1: 546, y1: 328, x2: 547, y2: 366 }, // East Ave
  { x1: 557, y1: 201, x2: 558, y2: 253 }, // Chapel Row
  { x1: 557, y1: 253, x2: 558, y2: 270 }, // Chapel Row
  { x1: 557, y1: 270, x2: 558, y2: 302 }, // Chapel Row
  { x1: 557, y1: 302, x2: 558, y2: 328 }, // Chapel Row
  { x1: 570, y1: 201, x2: 571, y2: 253 }, // Station Rd
  { x1: 570, y1: 253, x2: 571, y2: 270 }, // Station Rd
  { x1: 570, y1: 270, x2: 571, y2: 302 }, // Station Rd
  { x1: 570, y1: 302, x2: 571, y2: 328 }, // Station Rd
  { x1: 575, y1: 201, x2: 576, y2: 253 }, // Station Rd
  { x1: 575, y1: 253, x2: 576, y2: 270 }, // Station Rd
  { x1: 575, y1: 270, x2: 576, y2: 302 }, // Station Rd
  { x1: 575, y1: 302, x2: 576, y2: 328 }, // Station Rd
  { x1: 575, y1: 328, x2: 576, y2: 366 }, // Station Rd
  { x1: 575, y1: 366, x2: 576, y2: 411 }, // Station Rd
  { x1: 575, y1: 411, x2: 576, y2: 464 }, // Station Rd
  { x1: 587, y1: 201, x2: 588, y2: 253 }, // Observatory Row
  { x1: 587, y1: 253, x2: 588, y2: 270 }, // Observatory Row
  { x1: 587, y1: 270, x2: 588, y2: 302 }, // Observatory Row
  { x1: 592, y1: 302, x2: 593, y2: 328 }, // Mill Row
  { x1: 615, y1: 201, x2: 616, y2: 253 }, // Chapel Row
  { x1: 615, y1: 253, x2: 616, y2: 270 }, // Chapel Row
  { x1: 615, y1: 270, x2: 616, y2: 302 }, // Chapel Row
  { x1: 615, y1: 302, x2: 616, y2: 328 }, // Chapel Row
  { x1: 620, y1: 201, x2: 621, y2: 253 }, // Chapel Row
  { x1: 620, y1: 253, x2: 621, y2: 270 }, // Chapel Row
  { x1: 620, y1: 270, x2: 621, y2: 302 }, // Chapel Row
  { x1: 620, y1: 302, x2: 621, y2: 328 }, // Chapel Row
  { x1: 620, y1: 328, x2: 621, y2: 366 }, // Chapel Row
  { x1: 660, y1: 201, x2: 661, y2: 253 }, // East Orbital Rd
  { x1: 660, y1: 253, x2: 661, y2: 270 }, // East Orbital Rd
  { x1: 660, y1: 270, x2: 661, y2: 302 }, // East Orbital Rd
  { x1: 660, y1: 302, x2: 661, y2: 328 }, // East Orbital Rd
  { x1: 660, y1: 328, x2: 661, y2: 366 }, // East Orbital Rd
  { x1: 660, y1: 366, x2: 661, y2: 411 }, // East Orbital Rd
  { x1: 660, y1: 411, x2: 661, y2: 440 }, // East Orbital Rd
  { x1: 660, y1: 440, x2: 661, y2: 464 }, // East Orbital Rd
];
// @end:core-roads